# -*- coding: utf-8 -*-
"""bmi_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16985HL378mi6HdmBT9w38Fpb8Wwk6I7e
"""

import streamlit as st
import pandas as pd

def calculate_bmi(weight, height_cm):
    height_m = height_cm / 100
    bmi = weight / (height_m ** 2)
    return round(bmi, 2)

def get_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif 18.5 <= bmi < 24.9:
        return "Normal"
    elif 25 <= bmi < 29.9:
        return "Overweight"
    else:
        return "Obese"

def get_plan(category):
    plans = {
        "Underweight": {
            "meals": "High-protein meals, nuts, dairy, healthy fats.",
            "exercise": "Light weight training, yoga, walking."
        },
        "Normal": {
            "meals": "Balanced meals, fruits, vegetables, whole grains.",
            "exercise": "Daily walking, cycling, swimming."
        },
        "Overweight": {
            "meals": "Low-carb, high-fiber meals, limit sugar.",
            "exercise": "Cardio: walking, aerobics, light jogging."
        },
        "Obese": {
            "meals": "Low-calorie diet, avoid fried and sugary foods.",
            "exercise": "Beginner walking plan, low-impact aerobics."
        }
    }
    return plans[category]

st.title("💪 BMI Calculator with Health Suggestions")

name = st.text_input("Enter your name")
age = st.number_input("Enter your age", min_value=1, max_value=120)
gender = st.selectbox("Select your gender", ["Male", "Female", "Other"])
height = st.number_input("Height (in cm)", min_value=50.0, max_value=250.0)
weight = st.number_input("Weight (in kg)", min_value=10.0, max_value=300.0)

if st.button("Calculate BMI"):
    if name and height and weight:
        bmi = calculate_bmi(weight, height)
        category = get_category(bmi)
        plan = get_plan(category)

        st.success(f"{name}, your BMI is {bmi} and you are **{category}**.")
        st.subheader("🧃 Meal Plan:")
        st.write(plan["meals"])
        st.subheader("🏃 Light Exercises:")
        st.write(plan["exercise"])

        # Save user data to CSV
        df = pd.DataFrame([{
            "Name": name,
            "Age": age,
            "Gender": gender,
            "Height_cm": height,
            "Weight_kg": weight,
            "BMI": bmi,
            "Category": category
        }])

        try:
            existing = pd.read_csv("bmi_data.csv")
            df = pd.concat([existing, df], ignore_index=True)
        except FileNotFoundError:
            pass

        df.to_csv("bmi_data.csv", index=False)
        st.info("✅ Your data has been saved.")
    else:
        st.warning("Please fill in all fields.")

!pip install streamlit